export enum AvatarExpeditionStateEnum {
  AVATAR_EXPEDITION_NONE = 0,
  AVATAR_EXPEDITION_DOING = 1,
  AVATAR_EXPEDITION_FINISH_WAIT_REWARD = 2,
  AVATAR_EXPEDITION_CALLBACK_WAIT_REWARD = 3,
  AVATAR_EXPEDITION_LOCKED = 4
}