export enum GrantReasonEnum {
  INVALID = 0,
  GRANT_BY_QUEST = 1,
  GRANT_BY_TRIAL_AVATAR_ACTIVITY = 2,
  GRANT_BY_DUNGEON_ELEMENT_CHALLENGE = 3,
  GRANT_BY_MIST_TRIAL_ACTIVITY = 4,
  GRANT_BY_SUMO_ACTIVITY = 5,
  GRANT_REASON_Unk2700_ELPMDIEIOHP = 6,
  GRANT_REASON_Unk2700_FALPDBLGHJB = 7,
  GRANT_REASON_Unk2700_GAMADMGGMBC = 8,
  GRANT_REASON_Unk2800_FIIDJHAKMOI = 9,
}
