export enum GrantReasonEnum {
  INVALID = 0,
  GRANT_BY_QUEST = 1,
  GRANT_BY_TRIAL_AVATAR_ACTIVITY = 2,
  GRANT_BY_DUNGEON_ELEMENT_CHALLENGE = 3,
  GRANT_BY_MIST_TRIAL_ACTIVITY = 4,
  GRANT_BY_SUMO_ACTIVITY = 5,
  GRANT_BY_POTION_ACTIVITY = 6,
  GRANT_BY_CRYSTAL_LINK_ACTIVITY = 7,
  GRANT_BY_IRODORI_MASTER = 8,
  GRANT_BY_GM = 9,
  GRANT_BY_INSTABLE_SPRAY_ACTIVITY = 10,
  GRANT_BY_MUQADAS_POTION_ACTIVITY = 11,
  GRANT_BY_VINTAGE_HUNTING = 12,
  GRANT_BY_CHAR_AMUSEMENT = 13
}