export enum MailCollectState {
  MAIL_COLLECT_STATE_COLLECTIBLE_UNKNOWN = 0,
  MAIL_COLLECT_STATE_NOT_COLLECTIBLE = 1,
  MAIL_COLLECT_STATE_COLLECTIBLE_UNCOLLECTED = 2,
  MAIL_COLLECT_STATE_COLLECTIBLE_COLLECTED = 3,
}
