export enum QuitReasonEnum {
  INVALID = 0,
  HOST_NO_OTHER_PLAYER = 1,
  KICK_BY_HOST = 2,
  BACK_TO_MY_WORLD = 3,
  KICK_BY_HOST_LOGOUT = 4,
  KICK_BY_HOST_BLOCK = 5,
  BE_BLOCKED = 6,
  KICK_BY_HOST_ENTER_HOME = 7,
  HOST_SCENE_INVALID = 8,
  KICK_BY_PLAY = 9,
}
