export interface DropTree {
  DropId: string
  MinLevel: string
  MaxLevel: string
  Random: string
  Tier: string
  Leaf1Id: string
  Leaf1Count: string
  Leaf1Weight: string
  Leaf2Id: string
  Leaf2Count: string
  Leaf2Weight: string
  Leaf3Id: string
  Leaf3Count: string
  Leaf3Weight: string
  Leaf4Id: string
  Leaf4Count: string
  Leaf4Weight: string
  Leaf5Id: string
  Leaf5Count: string
  Leaf5Weight: string
  Leaf6Id: string
  Leaf6Count: string
  Leaf6Weight: string
  Leaf7Id: string
  Leaf7Count: string
  Leaf7Weight: string
  Leaf8Id: string
  Leaf8Count: string
  Leaf8Weight: string
  Leaf9Id: string
  Leaf9Count: string
  Leaf9Weight: string
  Leaf10Id: string
  Leaf10Count: string
  Leaf10Weight: string
  Leaf11Id: string
  Leaf11Count: string
  Leaf11Weight: string
  Leaf12Id: string
  Leaf12Count: string
  Leaf12Weight: string
  Leaf13Id: string
  Leaf13Count: string
  Leaf13Weight: string
  Leaf14Id: string
  Leaf14Count: string
  Leaf14Weight: string
  Leaf15Id: string
  Leaf15Count: string
  Leaf15Weight: string
  Leaf16Id: string
  Leaf16Count: string
  Leaf16Weight: string
  Leaf17Id: string
  Leaf17Count: string
  Leaf17Weight: string
  Leaf18Id: string
  Leaf18Count: string
  Leaf18Weight: string
  Leaf19Id: string
  Leaf19Count: string
  Leaf19Weight: string
  Leaf20Id: string
  Leaf20Count: string
  Leaf20Weight: string
  Leaf21Id: string
  Leaf21Count: string
  Leaf21Weight: string
  Leaf22Id: string
  Leaf22Count: string
  Leaf22Weight: string
  Leaf23Id: string
  Leaf23Count: string
  Leaf23Weight: string
  Leaf24Id: string
  Leaf24Count: string
  Leaf24Weight: string
  Leaf25Id: string
  Leaf25Count: string
  Leaf25Weight: string
}

type DropTreeList = DropTree[]

export default DropTreeList
