export enum FoundationStatusEnum {
  NONE = 0,
  INIT = 1,
  BUILDING = 2,
  BUILT = 3
}

export enum GadgetBornTypeEnum {
  GADGET_BORN_NONE = 0,
  GADGET_BORN_IN_AIR = 1,
  GADGET_BORN_PLAYER = 2,
  GADGET_BORN_MONSTER_HIT = 3,
  GADGET_BORN_MONSTER_DIE = 4,
  GADGET_BORN_GADGET = 5,
  GADGET_BORN_GROUND = 6
}

export enum GadgetPlayTypeEnum {
  GADGET_PLAY_NONE = 0,
  GADGET_PLAY_CRUSIBLE = 1
}

export enum MovingPlatformTypeEnum {
  MOVING_PLATFORM_NONE = 0,
  MOVING_PLATFORM_USE_CONFIG = 1,
  MOVING_PLATFORM_ABILITY = 2,
  MOVING_PLATFORM_ROUTE = 3
}