export enum SvrMsgIdEnum {
  MSG_UNKNOWN = 0,
  MSG_BLOCK_REFRESH_COUNTDOWN = 1,
  MSG_AVATAR_REVIVE_BY_STATUE = 2,
  MSG_DAILY_TASK_REWARD_MAX_NUM = 3,
  MSG_ROUTINE_TYPE_NOT_OPEN = 4,
  MSG_ROUTINE_TYPE_REWARD_MAX_NUM = 5,
  MSG_MECHANICUS_COIN_LIMIT = 6
}